spring.application.name=HotelManagementSystem

server.port= 7799
spring.datasource.url=jdbc:mysql://localhost:3306/HotelManagement?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=vaishnavi

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.error.include-message=always
server.error.include-binding-errors=always
logging.level.org.springframework.web=DEBUG